# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9541323ce2b4bea093a3987e3c462f9c"
name = "ShopBot"
handle = "shopbot-19"
application_url = "https://correspondence-screensavers-worldwide-relatively.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://correspondence-screensavers-worldwide-relatively.trycloudflare.com/auth/callback",
  "https://correspondence-screensavers-worldwide-relatively.trycloudflare.com/auth/shopify/callback",
  "https://correspondence-screensavers-worldwide-relatively.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
